#!/bin/bash
Fail()
{
    echo "FATAL($0): $1"
    exit 1
}

g++ -Wall -Werror -Ofast -o mandelzoom mandelzoom.cpp lodepng.cpp || Fail "Error building C++ code."
rm -rf movie || Fail "Error deleting movie directory."
mkdir movie || Fail "Error creating movie directory."
./mandelzoom movie 3 -0.74498410019 -0.13523854817 3.0e6 || Fail "Error running Mandelbrot Zoom program."
